import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Damazon.cpm%26oq%3Damazon.cpm%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDM3NDVqMGoyqAIAsAIB%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3D_K5war-DI_SdseMPgJGKoAI&q=EhAkBnQAAFZfPAE-owX6pnpCGPzdwtMGIjAc5F8G2WspMtNR1v5FRCAzm6gxR1J23iKB61hf4XlcudhcTi4ZWYCeHWnEV7HsaEMyAVJaAUM');
  await page.locator('iframe[name="a-pznxf3oigt3l"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Skip' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-pznxf3oigt3l"]').contentFrame().getByRole('button', { name: 'Next' }).click();
});